# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x06\n\x04Null\"\x12\n\x03Msg\x12\x0b\n\x03msg\x18\x01 \x01(\t2 \n\nLogService\x12\x12\n\x03Log\x12\x04.Msg\x1a\x05.Nullb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=17
  _NULL._serialized_end=23
  _MSG._serialized_start=25
  _MSG._serialized_end=43
  _LOGSERVICE._serialized_start=45
  _LOGSERVICE._serialized_end=77
# @@protoc_insertion_point(module_scope)
